export const COMPANY_DAYS_OFF = [
  {
    id: 1,
    isOnHoliday: true,
    startDate: '2021-06-01',
    endDate: '2021-06-13',
    user: {
      id: 'user1',
      firstName: 'Peter',
      lastName: 'Kansas',
      photo: undefined,
      occupation: 'Software Developer',
    },
  },
  {
    id: 2,
    isOnHoliday: true,
    startDate: '2021-06-10',
    endDate: '2021-07-10',
    user: {
      id: 'user2',
      firstName: 'Tom',
      lastName: 'Waist',
      photo: undefined,
      occupation: 'Software Developer',
    },
  },
  {
    id: 3,
    isOnHoliday: false,
    startDate: '2021-06-16',
    endDate: '2021-06-20',
    user: {
      id: 'user3',
      firstName: 'Kamila',
      lastName: 'Wysokogórska',
      photo: undefined,
      occupation: 'Software Developer',
    },
  },
  {
    id: 4,
    isOnHoliday: false,
    startDate: '2021-06-28',
    endDate: '2021-06-29',
    user: {
      id: 'user4',
      firstName: 'Ola',
      lastName: 'Nowak',
      photo: undefined,
      occupation: 'Software Developer',
    },
  },
  {
    id: 5,
    isOnHoliday: false,
    startDate: '2021-07-16',
    endDate: '2021-07-22',
    user: {
      id: 'user5',
      firstName: 'Ludwik',
      lastName: 'Chodak',
      photo: undefined,
      occupation: 'Software Developer',
    },
  },
  {
    id: 6,
    isOnHoliday: false,
    startDate: '2021-07-22',
    endDate: '2021-07-24',
    user: {
      id: 'user6',
      firstName: 'Paweł',
      lastName: 'Ogonek',
      photo: undefined,
      occupation: 'Software Developer',
    },
  },
]

export const USER_GROUPS_DAYS_OFF = [
  {
    groupId: 1,
    groupName: 'Smartsoft',
    users: [
      {
        id: 'user6',
        firstName: 'Paweł',
        lastName: 'Ogonek',
        photo: undefined,
        occupation: 'Software Engineer',
        holidays: {
          id: 1,
          isOnHoliday: false,
          startDate: '',
          endDate: '',
          isSickTime: false,
          description: undefined,
        },
      },
      {
        id: 'user1',
        firstName: 'Peter',
        lastName: 'Kansas',
        photo: undefined,
        occupation: 'Software Engineer',
        holidays: {
          id: 1,
          isOnHoliday: true,
          startDate: '2021-06-14',
          endDate: '2021-06-14',
          isSickTime: true,
          description: 'Terrible headache',
        },
      },
      {
        id: 'user9',
        firstName: 'Peter',
        lastName: 'Kansas',
        photo: undefined,
        occupation: 'Software Engineer',
        holidays: {
          id: 1,
          isOnHoliday: true,
          startDate: '2021-06-14',
          endDate: '2021-06-14',
          isSickTime: true,
          description: 'Terrible headache',
        },
      },
      {
        id: 'user2',
        firstName: 'Tom',
        lastName: 'Waist',
        photo: undefined,
        occupation: 'Software Engineer',
        holidays: {
          id: 2,
          isOnHoliday: false,
          startDate: '2021-06-04',
          endDate: '2021-06-10',
          isSickTime: false,
          description: 'Portugal',
        },
      },
      {
        id: 'user3',
        firstName: 'Kamila',
        lastName: 'Wysokogórska',
        photo: undefined,
        occupation: 'Software Engineer',
        holidays: {
          id: 1,
          isOnHoliday: false,
          startDate: '',
          endDate: '',
          isSickTime: false,
          description: undefined,
        },
      },
      {
        id: 'user4',
        firstName: 'Ola',
        lastName: 'Nowak',
        photo: undefined,
        occupation: 'Software Engineer',
        holidays: {
          id: 1,
          isOnHoliday: false,
          startDate: '',
          endDate: '',
          isSickTime: false,
          description: undefined,
        },
      },
      {
        id: 'user5',
        firstName: 'Kamila',
        lastName: 'Wysokogórska-Nowak',
        photo: undefined,
        occupation: 'Software Engineer',
        holidays: {
          id: 1,
          isOnHoliday: false,
          startDate: '',
          endDate: '',
          isSickTime: false,
          description: undefined,
        },
      },
      {
        id: 'user7',
        firstName: 'Ola',
        lastName: 'Nowak',
        photo: undefined,
        occupation: 'Software Engineer',
        holidays: {
          id: 1,
          isOnHoliday: false,
          startDate: '',
          endDate: '',
          isSickTime: false,
          description: undefined,
        },
      },
      {
        id: 'user8',
        firstName: 'Ola',
        lastName: 'Nowak',
        photo: undefined,
        occupation: 'Software Engineer',
        holidays: {
          id: 1,
          isOnHoliday: false,
          startDate: '',
          endDate: '',
          isSickTime: false,
          description: undefined,
        },
      },
    ],
  },
  {
    groupId: 2,
    groupName: 'FileCode',
    users: [
      {
        id: 'user2',
        firstName: 'Tom',
        lastName: 'Waist',
        photo: undefined,
        occupation: 'Software Engineer',
        holidays: {
          id: 2,
          isOnHoliday: true,
          startDate: '2021-06-04',
          endDate: '2021-06-10',
          isSickTime: true,
          description: 'Broken arm',
        },
      },
      {
        id: 'user3',
        firstName: 'Kamila',
        lastName: 'Wysokogórska',
        photo: undefined,
        occupation: 'Office Manager',
        holidays: {
          id: 3,
          isOnHoliday: false,
          startDate: '2021-06-10',
          endDate: '2021-06-15',
          isSickTime: false,
          description: 'Mountain trip',
        },
      },
      {
        id: 'user4',
        firstName: 'Ola',
        lastName: 'Nowak',
        photo: undefined,
        occupation: 'Software Engineer',
        holidays: {
          id: 4,
          isOnHoliday: false,
          startDate: '2021-06-10',
          endDate: '2021-06-15',
          isSickTime: false,
          description: undefined,
        },
      },
    ],
  },
  {
    groupId: 3,
    groupName: 'Softlab',
    users: [
      {
        id: 'user2',
        firstName: 'Tom',
        lastName: 'Waist',
        photo: undefined,
        occupation: 'Software Engineer',
        holidays: {
          id: 1,
          isOnHoliday: false,
          startDate: '',
          endDate: '',
          isSickTime: false,
          description: undefined,
        },
      },
      {
        id: 'user3',
        firstName: 'Kamila',
        lastName: 'Wysokogórska',
        photo: undefined,
        occupation: 'Software Engineer',
        holidays: {
          id: 3,
          isOnHoliday: false,
          startDate: '2021-06-10',
          endDate: '2021-06-15',
          isSickTime: false,
          description: 'Kayaking',
        },
      },
      {
        id: 'user4',
        firstName: 'Ola',
        lastName: 'Nowak',
        photo: undefined,
        occupation: 'Software Engineer',
        holidays: {
          id: 4,
          isOnHoliday: false,
          startDate: '2021-06-10',
          endDate: '2021-06-30',
          isSickTime: false,
          description: 'Indonesia',
        },
      },
    ],
  },
  {
    groupId: 4,
    groupName: 'Open Byte',
    users: [
      {
        id: 'user2',
        firstName: 'Tom',
        lastName: 'Waist',
        photo: undefined,
        occupation: 'Software Engineer',
        holidays: {
          id: 2,
          isOnHoliday: true,
          startDate: '2021-06-04',
          endDate: '2021-06-10',
          isSickTime: false,
          description: undefined,
        },
      },
      {
        id: 'user3',
        firstName: 'Kamila',
        lastName: 'Wysokogórska',
        photo: undefined,
        occupation: 'Software Engineer',
        holidays: {
          id: 3,
          isOnHoliday: true,
          startDate: '2021-06-10',
          endDate: '2021-06-15',
          isSickTime: false,
          description: undefined,
        },
      },
      {
        id: 'user4',
        firstName: 'Ola',
        lastName: 'Nowak',
        photo: undefined,
        occupation: 'Software Engineer',
        holidays: {
          id: 4,
          isOnHoliday: false,
          startDate: '2021-06-10',
          endDate: '2021-06-15',
          isSickTime: false,
          description: undefined,
        },
      },
    ],
  },
  {
    groupId: 5,
    groupName: 'Spaceware',
    users: [
      {
        id: 'user2',
        firstName: 'Tom',
        lastName: 'Waist',
        holidays: {
          id: 2,
          isOnHoliday: true,
          startDate: '2021-06-04',
          endDate: '2021-06-10',
        },
      },
      {
        id: 'user3',
        firstName: 'Kamila',
        lastName: 'Wysokogórska',
        holidays: {
          id: 3,
          isOnHoliday: true,
          startDate: '2021-06-10',
          endDate: '2021-06-15',
        },
      },
      {
        id: 'user4',
        firstName: 'Ola',
        lastName: 'Nowak',
        holidays: {
          id: 4,
          isOnHoliday: false,
          startDate: '2021-06-10',
          endDate: '2021-06-15',
        },
      },
    ],
  },
  {
    groupId: 6,
    groupName: 'Webrain',
    users: [
      {
        id: 'user2',
        firstName: 'Tom',
        lastName: 'Waist',
        holidays: {
          id: 2,
          isOnHoliday: true,
          startDate: '2021-06-04',
          endDate: '2021-06-10',
        },
      },
      {
        id: 'user3',
        firstName: 'Kamila',
        lastName: 'Wysokogórska',
        holidays: {
          id: 3,
          isOnHoliday: true,
          startDate: '2021-06-10',
          endDate: '2021-06-15',
        },
      },
    ],
  },
  {
    groupId: 7,
    groupName: 'Pharmic',
    users: [
      {
        id: 'user2',
        firstName: 'Tom',
        lastName: 'Waist',
        holidays: {
          id: 2,
          isOnHoliday: true,
          startDate: '2021-06-04',
          endDate: '2021-06-10',
        },
      },
      {
        id: 'user3',
        firstName: 'Kamila',
        lastName: 'Wysokogórska',
        holidays: {
          id: 3,
          isOnHoliday: true,
          startDate: '2021-06-10',
          endDate: '2021-06-15',
        },
      },
    ],
  },
  {
    groupId: 8,
    groupName: 'NMedical',
    users: [
      {
        id: 'user2',
        firstName: 'Tom',
        lastName: 'Waist',
        holidays: {
          id: 2,
          isOnHoliday: true,
          startDate: '2021-06-04',
          endDate: '2021-06-10',
        },
      },
      {
        id: 'user3',
        firstName: 'Kamila',
        lastName: 'Wysokogórska',
        holidays: {
          id: 3,
          isOnHoliday: true,
          startDate: '2021-06-10',
          endDate: '2021-06-15',
        },
      },
    ],
  },
  {
    groupId: 9,
    groupName: 'Encrypto',
    users: [
      {
        id: 'user2',
        firstName: 'Tom',
        lastName: 'Waist',
        holidays: {
          id: 2,
          isOnHoliday: true,
          startDate: '2021-06-04',
          endDate: '2021-06-10',
        },
      },
      {
        id: 'user3',
        firstName: 'Kamila',
        lastName: 'Wysokogórska',
        holidays: {
          id: 3,
          isOnHoliday: true,
          startDate: '2021-06-10',
          endDate: '2021-06-15',
        },
      },
    ],
  },
  {
    groupId: 10,
    groupName: 'Akademia',
    users: [
      {
        id: 'user2',
        firstName: 'Tom',
        lastName: 'Waist',
        holidays: {
          id: 2,
          isOnHoliday: true,
          startDate: '2021-06-04',
          endDate: '2021-06-10',
        },
      },
      {
        id: 'user3',
        firstName: 'Kamila',
        lastName: 'Wysokogórska',
        holidays: {
          id: 3,
          isOnHoliday: true,
          startDate: '2021-06-10',
          endDate: '2021-06-15',
        },
      },
    ],
  },
]
