export enum QueryKeys {
  USER = 'USER',
  ALL_USERS = 'ALL_USERS',
  ORGANIZATION = 'ORGANIZATION',
  POSTS = 'POSTS',
  USER_REQUESTS = 'USER_REQUESTS',
  ADD_COMMENT = 'ADD_COMMENT',
  ADD_REACTION = 'ADD_REACTION',
}
