fastlane_version "2.190.0"

before_all do
   yarn(command: "install", step_name: "install_dependencies")
   ensure_git_branch
   ensure_git_status_clean
   git_pull
end

platform :ios do
   # iOS Lanes
   desc "connect to App store api"
   lane :connect_to_app_store do
      app_store_connect_api_key(
         key_id: ENV["KEY_ID"],
         issuer_id: ENV["ISSUER_ID"],
         is_key_content_base64: false,
         key_content: ENV["IOS_AUTH_KEY"],
      )
   end
   
   # TODO - uncomment after connecting gh actions

   # desc "Fetch certificates and provisioning profiles"
   # lane :certificates do
   #    match(app_identifier: "com.holidaily", type: "development", readonly: true)
   #    match(app_identifier: "com.holidaily", type: "appstore", readonly: true)
   # end

   

   desc "Update Version number"
      private_lane :update_version do

       increment_build_number(xcodeproj: "./ios/Holidayly.xcodeproj")
       increment_version_number( xcodeproj: "./ios/Holidayly.xcodeproj") 
   
    end

   desc "Build the iOS application."

      lane :build do
         cocoapods(
            podfile: "./ios/Podfile",
            repo_update: true
          )
        connect_to_app_store
        update_version
        gym(scheme: "Holidayly", workspace: "./ios/Holidayly.xcworkspace")
   end

   desc "Ship to Testflight."
        lane :beta do
            build
            upload_to_testflight(username:ENV["TF_USERNAME"], app_identifier:ENV["APP_IDENTIFIER"], skip_submission: true,
            skip_waiting_for_build_processing: true)
   end
end

platform :android do
   # Android Lanes   

   desc "Bump build version"
   private_lane :bump_build_version do
   
      package = load_json(json_path: "./package.json")
      increment_version_code(gradle_file_path: "android/app/build.gradle")

      increment_version_name(
         gradle_file_path: "./android/app/build.gradle",
         version_name: package['version']
      )

   end

   desc "Android build and release to beta"
   lane :beta do
      bump_build_version
      gradle(task: "clean", project_dir: "./android/")
      gradle(task: "bundle", build_type: "Release", project_dir: "./android/")

      upload_to_play_store(
         package_name: ENV["ANDROID_PACKAGE_NAME"],
         track: "internal",
         json_key: "./android/app/holidaily-fastlane.json",
         aab: "./android/app/build/outputs/bundle/release/app-release.aab"
      )
  end

end
