import { Factory } from 'miragejs'
import { faker } from '@faker-js/faker'
import { getRandomValue } from 'utils/getRandomValue'

const colors = [
  '#FF88DC',
  '#390099',
  '#FFA756',
  '#BE8FF2',
  '#BE8FF2',
  '#80ED99',
  '#FEE610',
  '#8E94A5',
  '#FD8989',
  '#8DF4E7',
  '#91A6FF',
]

export const userFactory = Factory.extend({
  confirmed: true,
  email: faker.internet.email(),
  firstName: faker.name.firstName(),
  lastName: faker.name.lastName(),
  occupation: faker.name.jobTitle(),
  requests: [],
  language: 'en',
  userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length })),
  photo: null,
  role: 'Admin',
  availablePto: Math.round(Math.random() * 24),
  // @ts-ignore
  afterCreate(user, server) {
    server.createList('request', 10, { user })
  },
})

export const usersList = [
  {
    firstName: 'Peter',
    lastName: 'Kansas',
    photo: 'https://randomuser.me/api/portraits/men/1.jpg',
    occupation: 'Software Engineer',
    requests: [],
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length })),
  },
  {
    firstName: 'Tom',
    lastName: 'Waist',
    photo: 'https://randomuser.me/api/portraits/men/2.jpg',
    occupation: 'UI/UX Designer',
    requests: [],
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length })),
  },
  {
    firstName: 'Kamila',
    lastName: 'Wysokogórska',
    photo: 'https://randomuser.me/api/portraits/women/1.jpg',
    occupation: 'QA Tester',
    requests: [],
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length })),
  },
  {
    firstName: 'Ola',
    lastName: 'Nowak',
    photo: 'https://randomuser.me/api/portraits/women/17.jpg',
    occupation: 'Project Manager',
    requests: [],
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length })),
  },
  {
    firstName: 'Basia',
    lastName: 'Kowalska',
    photo: 'https://randomuser.me/api/portraits/women/2.jpg',
    occupation: 'UI/UX Designer',
    requests: [],
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length })),
  },
  {
    firstName: 'Roberta',
    lastName: 'Gardner',
    photo: 'https://randomuser.me/api/portraits/women/3.jpg',
    occupation: 'QA Tester',
    requests: [],
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length })),
  },
  {
    firstName: 'Ramon',
    lastName: 'Wheeler',
    photo: 'https://randomuser.me/api/portraits/men/3.jpg',
    occupation: 'Software Engineer',
    requests: [],
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length })),
  },
  {
    firstName: 'Ted',
    lastName: 'Rose',
    photo: 'https://randomuser.me/api/portraits/men/10.jpg',
    occupation: 'Software Engineer',
    requests: [],
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length })),
  },
  {
    firstName: 'Pedro',
    lastName: 'Soto',
    photo: 'https://randomuser.me/api/portraits/men/4.jpg',
    occupation: 'QA Tester',
    requests: [],
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length })),
  },
  {
    firstName: 'Dolores',
    lastName: 'King',
    photo: 'https://randomuser.me/api/portraits/women/5.jpg',
    occupation: 'UI/UX Designer',
    requests: [],
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length })),
  },
  {
    firstName: 'Bessie',
    lastName: 'Garcia',
    photo: 'https://randomuser.me/api/portraits/women/6.jpg',
    occupation: 'Software Engineer',
    requests: [],
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length })),
  },
  {
    firstName: 'Brent',
    lastName: 'Morris',
    photo: 'https://randomuser.me/api/portraits/men/11.jpg',
    occupation: 'QA Tester',
    requests: [],
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length })),
  },
  {
    firstName: 'Melanie',
    lastName: 'Holt',
    photo: 'https://randomuser.me/api/portraits/women/8.jpg',
    occupation: 'Software Engineer',
    requests: [],
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length })),
  },
  {
    firstName: 'Jimmie',
    lastName: 'Williams',
    photo: 'https://randomuser.me/api/portraits/men/9.jpg',
    occupation: 'UI/UX Designer',
    requests: [],
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length })),
  },
  {
    firstName: 'Frances',
    lastName: 'Hawkins',
    photo: 'https://randomuser.me/api/portraits/men/15.jpg',
    occupation: 'QA Tester',
    requests: [],
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length })),
  },
  {
    firstName: 'Stacey',
    lastName: 'Day',
    photo: 'https://randomuser.me/api/portraits/women/11.jpg',
    occupation: 'Project Manager',
    requests: [],
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length })),
  },
  {
    firstName: 'Leslie',
    lastName: 'Brown',
    photo: 'https://randomuser.me/api/portraits/women/12.jpg',
    occupation: 'Software Engineer',
    requests: [],
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length })),
  },
  {
    firstName: 'Eddie',
    lastName: 'Palmer',
    photo: 'https://randomuser.me/api/portraits/men/13.jpg',
    occupation: 'QA Tester',
    requests: [],
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length })),
  },
  {
    firstName: 'Darren',
    lastName: 'Franklin',
    photo: 'https://randomuser.me/api/portraits/men/14.jpg',
    occupation: 'UI/UX Designer',
    requests: [],
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length })),
  },
  {
    firstName: 'Heather',
    lastName: 'Vargas',
    photo: 'https://randomuser.me/api/portraits/women/15.jpg',
    occupation: 'QA Tester',
    requests: [],
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length })),
  },
  {
    firstName: 'Kathryn',
    lastName: 'Dixon',
    photo: 'https://randomuser.me/api/portraits/women/16.jpg',
    occupation: 'Software Engineer',
    requests: [],
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length })),
  },
  {
    firstName: 'Elmer',
    lastName: 'Gonzalez',
    photo: 'https://randomuser.me/api/portraits/men/17.jpg',
    occupation: 'UI/UX Designer',
    requests: [],
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length })),
  },
  {
    firstName: 'Riley',
    lastName: 'Ramos',
    photo: 'https://randomuser.me/api/portraits/men/18.jpg',
    occupation: 'QA Tester',
    requests: [],
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length })),
  },
  {
    firstName: 'Deann',
    lastName: 'Montgomery',
    photo: 'https://randomuser.me/api/portraits/men/19.jpg',
    occupation: 'Project Manager',
    requests: [],
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length })),
  },
  {
    firstName: 'Grace',
    lastName: 'Castillo',
    photo: 'https://randomuser.me/api/portraits/women/20.jpg',
    occupation: 'Software Engineer',
    requests: [],
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length })),
  },
  {
    firstName: 'Darlene',
    lastName: 'Lawson',
    photo: 'https://randomuser.me/api/portraits/women/21.jpg',
    occupation: 'QA Tester',
    requests: [],
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length })),
  },
  {
    firstName: 'Anita',
    lastName: 'Patterson',
    photo: 'https://randomuser.me/api/portraits/men/22.jpg',
    occupation: 'UI/UX Designer',
    requests: [],
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length })),
  },
  {
    firstName: 'Yvonne',
    lastName: 'Dunn',
    photo: 'https://randomuser.me/api/portraits/women/23.jpg',
    occupation: 'QA Tester',
    requests: [],
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length })),
  },
  {
    firstName: 'Alyssa',
    lastName: 'Richardson',
    photo: 'https://randomuser.me/api/portraits/women/24.jpg',
    occupation: 'Software Engineer',
    requests: [],
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length })),
  },
  {
    firstName: 'Terri',
    lastName: 'Graves',
    photo: 'https://randomuser.me/api/portraits/men/25.jpg',
    occupation: 'Software Engineer',
    requests: [],
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length })),
  },
  {
    firstName: 'Marvin',
    lastName: 'Ferguson',
    photo: 'https://randomuser.me/api/portraits/men/26.jpg',
    occupation: 'Project Manager',
    requests: [],
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length })),
  },
  {
    firstName: 'Jared',
    lastName: 'Oliver',
    photo: 'https://randomuser.me/api/portraits/men/27.jpg',
    occupation: 'QA Tester',
    requests: [],
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length })),
  },
  {
    firstName: 'Ray',
    lastName: 'Jacobs',
    photo: 'https://randomuser.me/api/portraits/men/28.jpg',
    occupation: 'UI/UX Designer',
    requests: [],
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length })),
  },
  {
    firstName: 'Everett',
    lastName: 'Ross',
    photo: 'https://randomuser.me/api/portraits/men/29.jpg',
    occupation: 'Software Engineer',
    requests: [],
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length })),
  },
  {
    firstName: 'Kev',
    lastName: 'Allen',
    photo: 'https://randomuser.me/api/portraits/men/30.jpg',
    occupation: 'Software Engineer',
    requests: [],
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length })),
  },
  {
    firstName: 'Hailey',
    lastName: 'Lynch',
    photo: 'https://randomuser.me/api/portraits/women/31.jpg',
    occupation: 'QA Tester',
    requests: [],
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length })),
  },
  {
    firstName: 'Dale',
    lastName: 'Steeves',
    photo: 'https://randomuser.me/api/portraits/men/32.jpg',
    occupation: 'UI/UX Designer',
    requests: [],
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length })),
  },
  {
    firstName: 'Joe',
    lastName: 'Day',
    photo: 'https://randomuser.me/api/portraits/men/33.jpg',
    occupation: 'Software Engineer',
    requests: [],
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length })),
  },
  {
    firstName: 'Levi',
    lastName: 'Castillo',
    photo: 'https://randomuser.me/api/portraits/men/34.jpg',
    occupation: 'QA Tester',
    requests: [],
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length })),
  },
  {
    firstName: 'Lena',
    lastName: 'Morrison',
    photo: 'https://randomuser.me/api/portraits/women/35.jpg',
    occupation: 'Project Manager',
    requests: [],
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length })),
  },
]
