import { Factory } from 'miragejs'
import { faker } from '@faker-js/faker'
import { getRandomValue } from 'utils/getRandomValue'

const colors = [
  '91A6FF#',
  '#4E70FF',
  '#FF88DC',
  '#80ED99',
  '#FAFF7F',
  '#E5ED22',
  '#EE4A16',
  '#E522AC',
  '#001D96',
  '#B7FF7F',
  '#B137EB',
  '#3BEFB9',
]

export const userFactory = Factory.extend({
  confirmed: true,
  email: faker.internet.email(),
  firstName: faker.name.firstName(),
  lastName: faker.name.lastName(),
  occupation: faker.name.jobTitle(),
  requests: [],
  teams: [],
  language: 'en',
  userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  photo: null,
  role: 'Admin',
  availablePto: Math.round(Math.random() * 24),
})
export const usersList = [
  {
    firstName: 'Peter',
    lastName: 'Kansas',
    photo: 'https://randomuser.me/api/portraits/men/1.jpg',
    occupation: 'Software Engineer',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
  {
    firstName: 'Tom',
    lastName: 'Waist',
    photo: 'https://randomuser.me/api/portraits/men/2.jpg',
    occupation: 'UI/UX Designer',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
  {
    firstName: 'Kamila',
    lastName: 'Wysokogórska',
    photo: 'https://randomuser.me/api/portraits/women/1.jpg',
    occupation: 'QA Tester',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
  {
    firstName: 'Ola',
    lastName: 'Nowak',
    photo: 'https://randomuser.me/api/portraits/women/17.jpg',
    occupation: 'Project Manager',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
  {
    firstName: 'Basia',
    lastName: 'Kowalska',
    photo: 'https://randomuser.me/api/portraits/women/2.jpg',
    occupation: 'UI/UX Designer',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
  {
    firstName: 'Roberta',
    lastName: 'Gardner',
    photo: 'https://randomuser.me/api/portraits/women/3.jpg',
    occupation: 'QA Tester',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
  {
    firstName: 'Ramon',
    lastName: 'Wheeler',
    photo: 'https://randomuser.me/api/portraits/men/3.jpg',
    occupation: 'Software Engineer',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
  {
    firstName: 'Ted',
    lastName: 'Rose',
    photo: 'https://randomuser.me/api/portraits/men/10.jpg',
    occupation: 'Software Engineer',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
  {
    firstName: 'Pedro',
    lastName: 'Soto',
    photo: 'https://randomuser.me/api/portraits/men/4.jpg',
    occupation: 'QA Tester',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
  {
    firstName: 'Dolores',
    lastName: 'King',
    photo: 'https://randomuser.me/api/portraits/women/5.jpg',
    occupation: 'UI/UX Designer',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
  {
    firstName: 'Bessie',
    lastName: 'Garcia',
    photo: 'https://randomuser.me/api/portraits/women/6.jpg',
    occupation: 'Software Engineer',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
  {
    firstName: 'Brent',
    lastName: 'Morris',
    photo: 'https://randomuser.me/api/portraits/men/11.jpg',
    occupation: 'QA Tester',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
  {
    firstName: 'Melanie',
    lastName: 'Holt',
    photo: 'https://randomuser.me/api/portraits/women/8.jpg',
    occupation: 'Software Engineer',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
  {
    firstName: 'Jimmie',
    lastName: 'Williams',
    photo: 'https://randomuser.me/api/portraits/men/9.jpg',
    occupation: 'UI/UX Designer',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
  {
    firstName: 'Frances',
    lastName: 'Hawkins',
    photo: 'https://randomuser.me/api/portraits/men/15.jpg',
    occupation: 'QA Tester',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
  {
    firstName: 'Stacey',
    lastName: 'Day',
    photo: 'https://randomuser.me/api/portraits/women/11.jpg',
    occupation: 'Project Manager',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
  {
    firstName: 'Leslie',
    lastName: 'Brown',
    photo: 'https://randomuser.me/api/portraits/women/12.jpg',
    occupation: 'Software Engineer',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
  {
    firstName: 'Eddie',
    lastName: 'Palmer',
    photo: 'https://randomuser.me/api/portraits/men/13.jpg',
    occupation: 'QA Tester',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
  {
    firstName: 'Darren',
    lastName: 'Franklin',
    photo: 'https://randomuser.me/api/portraits/men/14.jpg',
    occupation: 'UI/UX Designer',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
  {
    firstName: 'Heather',
    lastName: 'Vargas',
    photo: 'https://randomuser.me/api/portraits/women/15.jpg',
    occupation: 'QA Tester',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
  {
    firstName: 'Kathryn',
    lastName: 'Dixon',
    photo: 'https://randomuser.me/api/portraits/women/16.jpg',
    occupation: 'Software Engineer',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
  {
    firstName: 'Elmer',
    lastName: 'Gonzalez',
    photo: 'https://randomuser.me/api/portraits/men/17.jpg',
    occupation: 'UI/UX Designer',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
  {
    firstName: 'Riley',
    lastName: 'Ramos',
    photo: 'https://randomuser.me/api/portraits/men/18.jpg',
    occupation: 'QA Tester',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
  {
    firstName: 'Deann',
    lastName: 'Montgomery',
    photo: 'https://randomuser.me/api/portraits/men/19.jpg',
    occupation: 'Project Manager',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
  {
    firstName: 'Grace',
    lastName: 'Castillo',
    photo: 'https://randomuser.me/api/portraits/women/20.jpg',
    occupation: 'Software Engineer',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
  {
    firstName: 'Darlene',
    lastName: 'Lawson',
    photo: 'https://randomuser.me/api/portraits/women/21.jpg',
    occupation: 'QA Tester',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
  {
    firstName: 'Anita',
    lastName: 'Patterson',
    photo: 'https://randomuser.me/api/portraits/women/22.jpg',
    occupation: 'UI/UX Designer',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
  {
    firstName: 'Yvonne',
    lastName: 'Dunn',
    photo: 'https://randomuser.me/api/portraits/women/23.jpg',
    occupation: 'QA Tester',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
  {
    firstName: 'Alyssa',
    lastName: 'Richardson',
    photo: 'https://randomuser.me/api/portraits/women/24.jpg',
    occupation: 'Software Engineer',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
  {
    firstName: 'Terri',
    lastName: 'Graves',
    photo: 'https://randomuser.me/api/portraits/men/25.jpg',
    occupation: 'Software Engineer',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
  {
    firstName: 'Marvin',
    lastName: 'Ferguson',
    photo: 'https://randomuser.me/api/portraits/men/26.jpg',
    occupation: 'Project Manager',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
  {
    firstName: 'Jared',
    lastName: 'Oliver',
    photo: 'https://randomuser.me/api/portraits/men/27.jpg',
    occupation: 'QA Tester',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
  {
    firstName: 'Ray',
    lastName: 'Jacobs',
    photo: 'https://randomuser.me/api/portraits/men/28.jpg',
    occupation: 'UI/UX Designer',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
  {
    firstName: 'Everett',
    lastName: 'Ross',
    photo: 'https://randomuser.me/api/portraits/men/29.jpg',
    occupation: 'Software Engineer',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
  {
    firstName: 'Kev',
    lastName: 'Allen',
    photo: 'https://randomuser.me/api/portraits/men/30.jpg',
    occupation: 'Software Engineer',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
  {
    firstName: 'Hailey',
    lastName: 'Lynch',
    photo: 'https://randomuser.me/api/portraits/women/31.jpg',
    occupation: 'QA Tester',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
  {
    firstName: 'Dale',
    lastName: 'Steeves',
    photo: 'https://randomuser.me/api/portraits/men/32.jpg',
    occupation: 'UI/UX Designer',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
  {
    firstName: 'Joe',
    lastName: 'Day',
    photo: 'https://randomuser.me/api/portraits/men/33.jpg',
    occupation: 'Software Engineer',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
  {
    firstName: 'Levi',
    lastName: 'Castillo',
    photo: 'https://randomuser.me/api/portraits/men/34.jpg',
    occupation: 'QA Tester',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
  {
    firstName: 'Lena',
    lastName: 'Morrison',
    photo: 'https://randomuser.me/api/portraits/women/35.jpg',
    occupation: 'Project Manager',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
  {
    firstName: 'Dennis',
    lastName: 'Young',
    photo: 'https://randomuser.me/api/portraits/men/36.jpg',
    occupation: 'Software Developer',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
  {
    firstName: 'Darryl',
    lastName: 'Newman',
    photo: 'https://randomuser.me/api/portraits/men/37.jpg',
    occupation: 'Software Developer',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
  {
    firstName: 'Nellie',
    lastName: 'Ward',
    photo: 'https://randomuser.me/api/portraits/women/38.jpg',
    occupation: 'QA Tester',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
  {
    firstName: 'Beth',
    lastName: 'Gibson',
    photo: 'https://randomuser.me/api/portraits/women/39.jpg',
    occupation: 'Project Manager',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
  {
    firstName: 'Bruce',
    lastName: 'Gray',
    photo: 'https://randomuser.me/api/portraits/men/40.jpg',
    occupation: 'Software Developer',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
  {
    firstName: 'Erik',
    lastName: 'Banks',
    photo: 'https://randomuser.me/api/portraits/men/41.jpg',
    occupation: 'Software Developer',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
  {
    firstName: 'Esther',
    lastName: 'Wallace',
    photo: 'https://randomuser.me/api/portraits/women/42.jpg',
    occupation: 'Software Developer',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
  {
    firstName: 'Devon',
    lastName: 'Harvey',
    photo: 'https://randomuser.me/api/portraits/men/43.jpg',
    occupation: 'QA Tester',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
  {
    firstName: 'Emma',
    lastName: 'Henry',
    photo: 'https://randomuser.me/api/portraits/women/43.jpg',
    occupation: 'QA Tester',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
  {
    firstName: 'Jeff',
    lastName: 'Perry',
    photo: 'https://randomuser.me/api/portraits/men/43.jpg',
    occupation: 'QA Tester',
    userColor: getRandomValue(colors, faker.datatype.number({ min: 0, max: colors.length - 1 })),
  },
]
