name: Android Internal Test-Deploy New Minor
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true
      - name: Decode Service Account Key JSON File
        run: echo $GPLAY_SERVICE_ACCOUNT_KEY | base64 -di > android/app/holidaily-fastlane.json
        env:
          GPLAY_SERVICE_ACCOUNT_KEY: ${{ secrets.GPLAY_SERVICE_ACCOUNT_KEY }}
      - name: Decode Keystore
        run: gpg -d --passphrase "${{ secrets.KEYSTORE_PASSPHRASE }}" --batch android/app/HolidailyProd.keystore.gpg > android/app/HolidailyProd.keystore
      - name: validate JSON key
        run: bundle exec fastlane run validate_play_store_json_key json_key:android/app/holidaily-fastlane.json
      - name: Add keys to gradle.properties
        run: printf "HOLIDAILY_UPLOAD_STORE_PASSWORD=${{ secrets.HOLIDAILY_UPLOAD_STORE_PASSWORD }}\nHOLIDAILY_UPLOAD_KEY_PASSWORD=${{ secrets.HOLIDAILY_UPLOAD_KEY_PASSWORD }}" >> android/gradle.properties
      - name: Deploy android beta
        run: bundle exec fastlane android beta
        env:
          ANDROID_PACKAGE_NAME: com.holidayly
      - name: Commit version bump
        run: |
          PACKAGE_VERSION=$(sed -nr 's/^\s*\"version": "([0-9]{1,}\.[0-9]{1,}.*)",$/\1/p' package.json)
          git add ./package.json
          git add  ./fastlane/report.xml
          git add ./android/app/build.gradle
          git commit -m "bump to version $PACKAGE_VERSION"
          git push
