name: TESTFLIGHT | Publish to Testflight
on:
  workflow_dispatch:
    inputs:
      deploy_version:
        type: choice
        description: Type of new deployed version
        options:
          - patch
          - minor
          - major
jobs:
  deploy:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Prepare env file
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true
      - uses: actions/setup-node@v3
        with:
          node-version: 16.14
          cache: yarn
      - name: Restore Pods cache
        uses: actions/cache@v2
        with:
          path: |
            ios/Pods
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Bundle and Upload to Testflight
        run: bundle exec fastlane ios build_and_release_to_testflight
        env:
          APPLE_KEY_ID: ${{secrets.APPLE_KEY_ID}}
          APPLE_ISSUER_ID: ${{secrets.APPLE_ISSUER_ID}}
          IOS_AUTH_KEY_BASE64: ${{secrets.IOS_AUTH_KEY_BASE64}}
          MATCH_PASSWORD: ${{secrets.MATCH_PASSWORD}}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{secrets.MATCH_GIT_BASIC_AUTHORIZATION}}
          PAT: ${{secrets.PAT}}
          DEPLOY_VERSION: ${{ github.event.inputs.deploy_version }}
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
      - name: Set github user
        run: |
          git config --global user.name 'jan-kozinski'
          git config --global user.email 'jan-kozinski@users.noreply.github.com'
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: release/ios-${{ steps.package-version.outputs.current-version}}
          token: ${{secrets.PAT}}
          add-paths: |
            ./package.json
            ./fastlane/report.xml
            ./ios/Holidayly.xcodeproj/project.pbxproj
            ./ios/Holidayly/Info.plist
            ./ios/OneSignalNotificationServiceExtension/Info.plist
          title: [RELEASE]: iOS-${{ steps.package-version.outputs.current-version}}
