name: Open PR
on:
  workflow_dispatch:
    inputs:
      deploy_version:
        type: choice
        description: Type of new deployed version
        options:
          - patch
          - minor
          - major
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
      - name: Bump versions
        run: bundle exec fastlane android bump_build_version
      - name: Commit version bump
        run: |
          git config --global user.name 'jan-kozinski'
          git config --global user.email 'jan-kozinski@users.noreply.github.com'
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          base: staging
          branch: test-${{ steps.package-version.outputs.current-version}}
          token: ${{secrets.PAT}}
          add-paths: |
            ./package.json
            ./fastlane/report.xml
            ./android/app/build.gradle
